services:
  - type: web
    name: pci-project
    env: node
    rootDir: payment-portal
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    autoDeploy: true
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20

